### ISSUE TITLE
Design question

### ISSUE THREAD

**Issue by spex66** [andychase/reparse#12]
Hi @andychase 
I know that I'm late to the party, but stumbled about your `reparse` project, which looks promising for my requirements (maintainability / unstructured text input)

One question about your design, I'm curious if you can remember:
* why have you declared "groups" explicit in expression-yaml, and not relied on named regex groups instead? => `?P<namedgroup>reg expression`
* and why have you dropped development, because you found something better?

and thx for the inspiration using `re.scanner()` btw, wasn't aware of this one before :)

**Comment by andychase** [comment]
Groups are a collection of regex patterns, like dates can be many regex
forms (2019/07/01 2019-08-1, etc)

I just lost interest. I developed this for web crawling system that could
collect al the dates on the internet. Also I'm somewhat busy these days
with work and grad school.

It's not a bad system. Pyparsing might be another to consider. The reasons
I built this was regex supports fuzzy matching, something I never ended up
using but it's there. My system can also be deployed to javascript (my
project date_machine is an example of this), which might be a killer
feature to you or not.

**Comment by andychase** [comment]
Oh I misunderstood the group question (I replied to this as I woke up). I used unnamed groups instead of named groups partially because I didn't like the syntax, but also because I was copying a lot of regex from regex sites and they used unnamed formats.

**Comment by andychase** [comment]
Oh one more thing on that.. I realized the REAL reason.  Keep in mind what my system does it combine a ton of regex together, so using named syntax I would have to re-write all of those names since you can't have two groups with the same name. Using the unnamed format I can just concat the regex parts together and keep track of the order of the groups.

So actually the design wouldn't work unless I wanted to parse and re-write the input regex strings which would be a nightmare.

**Comment by spex66** [comment]
Really appreciate your feedback and explanations!
Let's see how far (and quick) I get to my goal with your approach :)
